### ISSUE TITLE
Allow colours to be customisable

### ISSUE THREAD

**Issue by NoelAbrahams** [tscpp/vscode-knockout-binding-support#4]
In the following

```html
<input type="text" data-bind="textInput:myValue" />
```

The colours of the syntax elements `data-bind`, `textInput`, and `myValue` should be customisable via settings.json

**Comment by tscpp** [comment]
I acknowledge that there's room for improvement in highlighting binding attributes. However, I haven't seen a detailed description of the specific issue you're facing. I would appreciate it if you could create a new issue where you outline the specific aspects that are lacking.
